spring:
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:sample;DATABASE_TO_UPPER=false;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;TRACE_LEVEL_SYSTEM_OUT=1;INIT=RUNSCRIPT FROM 'sql/db_init.h2.sql'
        username: sa
        max-wait: 1000
        max-active: 50
        test-on-borrow: true
        
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        
        hibernate:
            ddl-auto: create
            
            hbm2ddl:
                import_files: 'classpath:/sql/data-h2.sql'

broker:
    bootstrapServer: localhost:9092
    producer:
        linger-time-ms: 0

